import { Message } from '../models/Message.js';
import { Lead } from '../models/Lead.js';
import { Conversation } from '../models/Conversation.js';
import { aiService } from '../services/ai.service.js';
import { emailService } from '../services/email.service.js';

export const getMessages = async (req, res) => {
  try {
    const { status, lead_id } = req.query;
    const query = {};
    if (status) query.status = status;
    if (lead_id) query.lead_id = lead_id;

    const messages = await Message.find(query)
      .populate('lead_id')
      .sort({ created_at: -1 });

    res.json({ success: true, count: messages.length, data: messages });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

export const getPendingApprovals = async (req, res) => {
  try {
    const pending = await Message.find({ status: 'PENDING_APPROVAL' })
      .populate({
        path: 'lead_id',
        populate: { path: 'analysis' }
      })
      .sort({ created_at: -1 });

    res.json({ success: true, count: pending.length, data: pending });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

export const approveMessage = async (req, res) => {
  try {
    const { id } = req.params;
    const { content, subject } = req.body;

    const message = await Message.findById(id).populate('lead_id');
    if (!message) return res.status(404).json({ success: false, error: 'Message not found' });

    if (content) message.content = content;
    if (subject) message.subject = subject;
    message.status = 'APPROVED';
    message.approval_source = 'WEB_DASHBOARD';
    await message.save();

    if (message.lead_id) {
      message.lead_id.status = 'APPROVED';
      await message.lead_id.save();
    }

    // Immediately dispatch via Email service
    emailService.sendEmail({
      to: message.lead_id.email,
      subject: message.subject,
      text: message.content,
      messageId: message._id,
      leadId: message.lead_id._id
    }).catch(e => console.warn('Email dispatch warning:', e.message));

    res.json({ success: true, message: 'Message approved and queued for sending', data: message });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

export const rejectMessage = async (req, res) => {
  try {
    const { id } = req.params;
    const { reason } = req.body;

    const message = await Message.findByIdAndUpdate(
      id,
      { status: 'REJECTED', rejection_reason: reason || 'Rejected by user' },
      { new: true }
    );

    res.json({ success: true, message: 'Message rejected', data: message });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

export const regeneratePitch = async (req, res) => {
  try {
    const { id } = req.params;
    const { instructions, tone } = req.body;

    const message = await Message.findById(id).populate({
      path: 'lead_id',
      populate: { path: 'analysis' }
    });
    if (!message || !message.lead_id) return res.status(404).json({ success: false, error: 'Message or Lead not found' });

    const lead = message.lead_id;
    const analysis = lead.analysis;

    const prompt = `
Regenerate cold outreach email for ${lead.business_name} (${lead.industry}, ${lead.city || 'India'}).
Tone: ${tone || 'Persuasive, highly tailored, direct and concise'}.
Special Instructions: ${instructions || 'Emphasize fast delivery and immediate appointment booking growth'}.
Key Observations: ${analysis?.pain_points?.join(', ') || 'No modern booking workflow'}.

Return JSON:
{
  "subject": "Tailored subject line",
  "body": "Hi ${lead.business_name} team,\\n\\n..."
}
`;

    const response = await aiService.executeWithFallback(prompt, 'You are an elite B2B email copywriter.', 'MESSAGE_GEN', lead._id);
    let newSubject = `Opportunity for ${lead.business_name}'s website`;
    let newBody = `Hi ${lead.business_name} team,\n\nI was looking into ${lead.industry} in ${lead.city || 'your area'} and noticed a clear opportunity to modernize your patient appointment flow.\n\nAt Leovexa Technologies, we implement automated booking systems that convert visitors directly into confirmed inquiries.\n\nWould you be open to a 2-minute quick walkthrough this week?\n\nBest regards,\nLeovexa Technologies`;

    try {
      const parsed = JSON.parse(response.text.match(/\{[\s\S]*\}/)?.[0]);
      if (parsed.subject) newSubject = parsed.subject;
      if (parsed.body) newBody = parsed.body;
    } catch (e) {}

    message.subject = newSubject;
    message.content = newBody;
    message.status = 'PENDING_APPROVAL';
    await message.save();

    res.json({ success: true, message: 'Pitch regenerated by AI', data: message });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

export const simulateInboundReply = async (req, res) => {
  try {
    const { lead_id, reply_text } = req.body;
    if (!lead_id) return res.status(400).json({ success: false, error: 'lead_id is required' });

    const text = reply_text || 'Yes, we are interested in upgrading our website and booking system. Please share your portfolio and pricing.';
    const result = await emailService.handleInboundReply({
      leadId: lead_id,
      replyText: text
    });

    res.json({
      success: true,
      message: 'Simulated inbound reply received, analyzed by AI, and alert sent!',
      data: result
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

export const getConversations = async (req, res) => {
  try {
    const conversations = await Conversation.find()
      .populate('lead_id')
      .sort({ updated_at: -1 });

    res.json({ success: true, count: conversations.length, data: conversations });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

// Get Multi-Touch Follow-up Sequences across all contacted/active leads
export const getFollowupSequences = async (req, res) => {
  try {
    const leads = await Lead.find({
      status: { $in: ['CONTACTED', 'QUALIFIED', 'APPROVED', 'MEETING_BOOKED', 'CONVERTED'] }
    }).sort({ updated_at: -1 }).limit(50);

    const sequences = [];
    for (const lead of leads) {
      const messages = await Message.find({ lead_id: lead._id }).sort({ created_at: 1 });
      const initial = messages.find(m => m.type === 'INITIAL');
      const followup1 = messages.find(m => m.type === 'FOLLOWUP_1');
      const followup2 = messages.find(m => m.type === 'FOLLOWUP_2');

      // Compute schedule & current step
      let currentStep = 'Step 1: Initial Outreach';
      let nextAction = 'Initial pitch sending';
      let nextRunDate = null;

      if (initial && initial.status === 'SENT') {
        const sentDate = new Date(initial.sent_at || initial.delivered_at || initial.created_at);
        const day3Date = new Date(sentDate.getTime() + 3 * 24 * 60 * 60 * 1000);
        const day7Date = new Date(sentDate.getTime() + 7 * 24 * 60 * 60 * 1000);

        if (!followup1) {
          currentStep = 'Step 1: Contacted (Waiting for Day 3)';
          nextAction = 'Automated Day 3 Value Follow-up';
          nextRunDate = day3Date;
        } else if (followup1.status === 'SENT') {
          if (!followup2) {
            currentStep = 'Step 2: Day 3 Sent (Waiting for Day 7)';
            nextAction = 'Automated Day 7 Breakup Pitch';
            nextRunDate = day7Date;
          } else {
            currentStep = 'Step 3: Full 3-Touch Sequence Completed';
            nextAction = 'Sequence Finished';
            nextRunDate = null;
          }
        } else {
          currentStep = 'Step 2: Day 3 Follow-up Queued';
          nextAction = 'Pending Dispatch';
          nextRunDate = day3Date;
        }
      }

      sequences.push({
        lead_id: lead._id,
        business_name: lead.business_name,
        email: lead.email,
        country: lead.country || 'USA',
        lead_score: lead.lead_score,
        lead_status: lead.status,
        current_step: currentStep,
        next_action: nextAction,
        next_run_date: nextRunDate,
        steps: {
          initial: initial ? { id: initial._id, status: initial.status, subject: initial.subject, content: initial.content, sent_at: initial.sent_at } : null,
          followup_1: followup1 ? { id: followup1._id, status: followup1.status, subject: followup1.subject, content: followup1.content, sent_at: followup1.sent_at } : null,
          followup_2: followup2 ? { id: followup2._id, status: followup2.status, subject: followup2.subject, content: followup2.content, sent_at: followup2.sent_at } : null
        }
      });
    }

    res.json({
      success: true,
      count: sequences.length,
      data: sequences
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

// Manually Trigger Instant Follow-up Dispatch for a Lead
export const triggerManualFollowup = async (req, res) => {
  try {
    const { lead_id, step = 'FOLLOWUP_1' } = req.body;
    if (!lead_id) return res.status(400).json({ success: false, error: 'lead_id is required' });

    const lead = await Lead.findById(lead_id);
    if (!lead) return res.status(404).json({ success: false, error: 'Lead not found' });

    const prompt = `
Generate a quick, polite, non-pushy ${step === 'FOLLOWUP_2' ? 'Day 7 Final / Breakup' : 'Day 3 Value Bump'} cold email for Leovexa Technologies (https://leovexa.in).
Lead: ${lead.business_name} in ${lead.city || 'local area'} (${lead.industry}).
Keep it concise, high-converting, under 60 words.

Return JSON:
{
  "subject": "${step === 'FOLLOWUP_2' ? 'Final note regarding' : 'Quick follow-up on'} ${lead.business_name}'s website / booking flow",
  "body": "Hi ${lead.business_name} team,\\n\\n..."
}
`;

    const response = await aiService.executeWithFallback(prompt, 'You are an email copywriter.', 'MESSAGE_GEN', lead._id);
    let json = {
      subject: `Following up on ${lead.business_name}'s website`,
      body: `Hi ${lead.business_name} team,\n\nFollowing up briefly on my earlier note. Have you had a chance to review ideas for updating ${lead.business_name}'s online patient booking flow?\n\nHappy to share a quick 2-minute video audit if you're open.\n\nBest,\nLeovexa Team\nhttps://leovexa.in`
    };

    try {
      const parsed = JSON.parse(response.text.match(/\{[\s\S]*\}/)?.[0]);
      if (parsed.subject && parsed.body) json = parsed;
    } catch (e) {}

    const msg = await Message.create({
      lead_id: lead._id,
      campaign_id: lead.campaign_id,
      channel: 'EMAIL',
      direction: 'OUTBOUND',
      type: step,
      subject: json.subject,
      content: json.body,
      status: 'APPROVED',
      approval_source: 'WEB_DASHBOARD',
      ai_generated: true
    });

    // Immediate dispatch via Gmail
    emailService.sendEmail({
      to: lead.email,
      subject: msg.subject,
      text: msg.content,
      messageId: msg._id,
      leadId: lead._id
    }).catch(e => console.warn('Manual followup dispatch notice:', e.message));

    res.json({
      success: true,
      message: `${step === 'FOLLOWUP_2' ? 'Day 7 Final' : 'Day 3'} Follow-up drafted and queued for live sending to ${lead.email}!`,
      data: msg
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};
